<script lang="ts">
	import { enhance } from '$app/forms';
	import { Button } from '$lib/components/ui/button';
  	import { Checkbox } from '$lib/components/ui/checkbox';
    import * as Field from '$lib/components/ui/field';
	import { Label } from '$lib/components/ui/label';
	import MultiSelect, { type Option } from 'svelte-multiselect'
	import { createToastEnhance } from '$lib/form-toast';

	let { data, form } = $props();

	const websitesOptions: Option[] = $derived(data.websites.map(w => {
		return {
			value: String(w.id ?? ''),
			label: w.url
		}
	}));

	const deviceOptions: Option[] = $derived(data.devices.map(d => {
		return {
			value: d.name,
			label: `${d.name} (${d.resolution})`,
			group: d.isMobile ? 'Mobile' : 'Desktop'
		}
	}));

	const optionValue = (option: Option | null | undefined): string => {
		if (option == null) return '';
		if (typeof option === 'string' || typeof option === 'number') return String(option);
		return String(option.value ?? '');
	};

	let selectedWebsites: Option | null = $derived(
		form?.values?.website
			? websitesOptions.find(w => optionValue(w) === form?.values?.website) || null
			: data?.prefillWebsiteId
				? websitesOptions.find(w => optionValue(w) === data.prefillWebsiteId) || null
				: null
	);
	let selectedDevices: Option[] = $derived(
		form?.values?.devices
			? deviceOptions.filter(d => form?.values?.devices.includes(optionValue(d)))
			: deviceOptions.filter(d => optionValue(d) === "Desktop Chrome")
	);

	let wcagSelected = $state(true);
	let seoSelected = $state(true);
	let securitySelected = $state(false);
	let scheduleSelected = $state(false);

	$effect(() => {
		if (!form?.values?.types) return;
		wcagSelected = form.values.types.includes('wcag');
		seoSelected = form.values.types.includes('seo');
		securitySelected = form.values.types.includes('security');
	});
</script>

<div class="p-4 lg:p-6 max-w-xl space-y-4">
	<h2 class="text-xl font-semibold">Create Job</h2>
	<p class="text-sm text-muted-foreground">Job Queue tasks are created automatically and picked up by a background worker. Check back in a few minutes for the results.</p>

	{#if form?.error}
		<p class="text-sm text-destructive">{form.error}</p>
	{/if}

	<form
		method="POST"
		class="space-y-3"
		use:enhance={createToastEnhance({
			success: 'Job created successfully.',
			error: 'Failed to create job.'
		})}
	>
		<div class="flex w-full flex-col gap-1.5">
			<Label for="website" class="text-lg">Website</Label>
			<MultiSelect bind:value={selectedWebsites} options={websitesOptions} maxSelect={1} required />
			{#if selectedWebsites}
			<input type="hidden" name="website" value={optionValue(selectedWebsites)} />
			{/if}
		</div>
		<Field.Set>
			<Field.Legend>Tools to run</Field.Legend>
			<Field.Description>The recommended tools are pre-selected. Keep in mind that the screenshots are generated by the WCAG tool.</Field.Description>
			<Field.Group class="columns-2 block">
				<Field.Field orientation="horizontal" class="mb-2">
					<Checkbox name="types" id="tool-seo" bind:checked={seoSelected} value="seo" />
					<Field.Label for="tool-seo" class="font-normal">
						SEO
					</Field.Label>
				</Field.Field>
				<Field.Field orientation="horizontal" class="mb-2">
					<Checkbox name="types" id="tool-wcag" bind:checked={wcagSelected} value="wcag" />
					<Field.Label for="tool-wcag" class="font-normal">
						WCAG
					</Field.Label>
				</Field.Field>
				<Field.Field orientation="horizontal" class="mb-2">
					<Checkbox name="types" id="tool-domain" checked={form?.values?.types.includes('domain') ?? true} value="domain" />
					<Field.Label for="tool-domain" class="font-normal">
						Domain
					</Field.Label>
				</Field.Field>
				<Field.Field orientation="horizontal" class="mb-2">
					<Checkbox name="types" id="tool-ssl" checked={form?.values?.types.includes('ssl') ?? true} value="ssl" />
					<Field.Label for="tool-ssl" class="font-normal">
						SSL
					</Field.Label>
				</Field.Field>
				<Field.Field orientation="horizontal" class="mb-2">
					<Checkbox name="types" id="tool-whois" value="whois" checked={form?.values?.types.includes('whois')} />
					<Field.Label for="tool-whois" class="font-normal">
						Whois
					</Field.Label>
				</Field.Field>
				<Field.Field orientation="horizontal" class="mb-2">
					<Checkbox name="types" id="tool-security" bind:checked={securitySelected} value="security" />
					<Field.Label for="tool-security" class="font-normal">
						Security
					</Field.Label>
				</Field.Field>
				<Field.Field orientation="horizontal" class="mb-2">
					<Checkbox name="types" id="tool-stress" value="stress" checked={form?.values?.types.includes('stress')} />
					<Field.Label for="tool-stress" class="font-normal">
						Stress
					</Field.Label>
				</Field.Field>
				<Field.Field orientation="horizontal" class="mb-2">
					<Checkbox name="types" id="tool-mail" value="mail" checked={form?.values?.types.includes('mail')} />
					<Field.Label for="tool-mail" class="font-normal">
						Mail
					</Field.Label>
				</Field.Field>
			</Field.Group>
			<Field.Separator />
			<Field.Group>
				{#if seoSelected}
				<div class="rounded-md border p-3 space-y-3">
					<Field.Field orientation="horizontal">
						<Checkbox name="seo_crawl_enabled" id="seo-crawl-enabled" checked />
						<Field.Label for="seo-crawl-enabled" class="font-normal">Enable SEO crawl and broken-link checks</Field.Label>
					</Field.Field>
					<div class="grid grid-cols-2 gap-3">
						<div>
							<Label for="seo-max-pages">SEO max pages</Label>
							<input id="seo-max-pages" name="seo_max_pages" type="number" min="1" max="1000" value="10" class="border-input bg-background w-full rounded-md border px-3 py-2 text-sm" />
						</div>
						<div>
							<Label for="seo-concurrency">SEO concurrency</Label>
							<input id="seo-concurrency" name="seo_concurrency" type="number" min="1" max="20" value="3" class="border-input bg-background w-full rounded-md border px-3 py-2 text-sm" />
						</div>
					</div>
				</div>
				{/if}
				{#if wcagSelected}
				<div class="flex w-full flex-col gap-1.5">
					<Label for="devices" class="text-lg">WCAG Device Targets</Label>
					<MultiSelect bind:value={selectedDevices} options={deviceOptions} maxSelect={4} />
				</div>
				{#each selectedDevices as device}
				<input type="hidden" name="devices" value={optionValue(device)} />
				{/each}
				<div class="rounded-md border p-3 space-y-3">
					<Field.Field orientation="horizontal">
						<Checkbox name="wcag_crawl_enabled" id="wcag-crawl-enabled" checked />
						<Field.Label for="wcag-crawl-enabled" class="font-normal">Crawl in WCAG container and scan representative templates</Field.Label>
					</Field.Field>
					<div class="grid grid-cols-3 gap-3">
						<div>
							<Label for="wcag-max-pages">WCAG max pages</Label>
							<input id="wcag-max-pages" name="wcag_max_pages" type="number" min="1" max="200" value="12" class="border-input bg-background w-full rounded-md border px-3 py-2 text-sm" />
						</div>
						<div>
							<Label for="wcag-max-depth">WCAG max depth</Label>
							<input id="wcag-max-depth" name="wcag_max_depth" type="number" min="1" max="10" value="2" class="border-input bg-background w-full rounded-md border px-3 py-2 text-sm" />
						</div>
						<div>
							<Label for="wcag-url-mode">WCAG URLs</Label>
							<select id="wcag-url-mode" name="wcag_url_mode" class="border-input bg-background w-full rounded-md border px-3 py-2 text-sm">
								<option value="representative">Representative templates</option>
								<option value="selected">Selected URLs</option>
								<option value="manual">Manual URLs only</option>
							</select>
						</div>
					</div>
				</div>
				{/if}
				{#if securitySelected}
				<div class="rounded-md border p-3 space-y-3">
					<div class="grid grid-cols-2 gap-3">
						<div>
							<Label for="security-scope">Wapiti scope</Label>
							<select id="security-scope" name="security_scope" class="border-input bg-background w-full rounded-md border px-3 py-2 text-sm">
								<option value="root">Root/folder</option>
								<option value="domain">Domain</option>
							</select>
						</div>
						<div>
							<Label for="nuclei-discovery">Nuclei URLs</Label>
							<select id="nuclei-discovery" name="nuclei_discovery" class="border-input bg-background w-full rounded-md border px-3 py-2 text-sm">
								<option value="none">Root only</option>
								<option value="katana">Katana discovery</option>
								<option value="selected_urls">Selected website URLs</option>
							</select>
						</div>
					</div>
				</div>
				{/if}
			</Field.Group>
		</Field.Set>
		<Field.Set>
			<Field.Legend>Schedule</Field.Legend>
			<Field.Description>Create a recurring scan from this same website, tools, and options.</Field.Description>
			<Field.Field orientation="horizontal">
				<Checkbox name="schedule_enabled" id="schedule-enabled" bind:checked={scheduleSelected} />
				<Field.Label for="schedule-enabled" class="font-normal">Create schedule</Field.Label>
			</Field.Field>
			{#if scheduleSelected}
			<div>
				<Label for="schedule-cron">Cron (UTC)</Label>
				<input id="schedule-cron" name="schedule_cron" value="0 0 * * *" class="border-input bg-background w-full rounded-md border px-3 py-2 text-sm font-mono" />
			</div>
			{/if}
		</Field.Set>
		<div class="flex items-center gap-3">
			<Button type="submit" size="lg">Create</Button>
			<Button href="/jobs" size="lg" variant="outline">Cancel</Button>
		</div>
	</form>
</div>
