<script lang="ts">
	import { Button } from '$lib/components/ui/button';
  	import { Checkbox } from '$lib/components/ui/checkbox';
    import * as Field from '$lib/components/ui/field';
	import { Label } from '$lib/components/ui/label';
	import MultiSelect, { type Option } from 'svelte-multiselect'

	let { data, form } = $props();

	const websitesOptions: Option[] = $derived(data.websites.map(w => {
		return {
			value: (w.id as unknown as string).split(':')[1],
			label: w.url
		}
	}));

	const deviceOptions: Option[] = $derived(data.devices.map(d => {
		return {
			value: d.name,
			label: `${d.name} (${d.resolution})`,
			group: d.isMobile ? 'Mobile' : 'Desktop'
		}
	}));

	const optionValue = (option: Option | null | undefined): string => {
		if (option == null) return '';
		if (typeof option === 'string' || typeof option === 'number') return String(option);
		return String(option.value ?? '');
	};

	let selectedWebsites: Option | null = $derived(
		form?.values?.website
			? websitesOptions.find(w => optionValue(w) === form?.values?.website) || null
			: data?.prefillWebsiteId
				? websitesOptions.find(w => optionValue(w) === data.prefillWebsiteId) || null
				: null
	);
	let selectedDevices: Option[] = $derived(
		form?.values?.devices
			? deviceOptions.filter(d => form?.values?.devices.includes(optionValue(d)))
			: deviceOptions.filter(d => optionValue(d) === "Desktop Chrome")
	);

	let wcagSelected = $derived(form?.values?.types.includes('wcag') ?? true);
</script>

<div class="p-4 lg:p-6 max-w-xl space-y-4">
	<h2 class="text-xl font-semibold">Create Job</h2>
	<p class="text-sm text-muted-foreground">Job Queue tasks are created automatically and picked up by a background worker. Check back in a few minutes for the results.</p>

	{#if form?.error}
		<p class="text-sm text-destructive">{form.error}</p>
	{/if}

	<form method="POST" class="space-y-3">
		<div class="flex w-full flex-col gap-1.5">
			<Label for="website" class="text-lg">Website</Label>
			<MultiSelect bind:value={selectedWebsites} options={websitesOptions} maxSelect={1} required />
			{#if selectedWebsites}
			<input type="hidden" name="website" value={optionValue(selectedWebsites)} />
			{/if}
		</div>
		<Field.Set>
			<Field.Legend>Tools to run</Field.Legend>
			<Field.Description>The recommended tools are pre-selected. Keep in mind that the screenshots are generated by the WCAG tool.</Field.Description>
			<Field.Group class="columns-2 block">
				<Field.Field orientation="horizontal" class="mb-2" title="Probing is necessary for any other tool to run">
					<Checkbox id="tool-probe" checked={true} disabled />
					<Field.Label for="tool-probe" class="font-normal">
						Probe
					</Field.Label>
				</Field.Field>
				<Field.Field orientation="horizontal" class="mb-2">
					<Checkbox name="types" id="tool-seo" checked={form?.values?.types.includes('seo') ?? true} value="seo" />
					<Field.Label for="tool-seo" class="font-normal">
						SEO
					</Field.Label>
				</Field.Field>
				<Field.Field orientation="horizontal" class="mb-2">
					<Checkbox name="types" id="tool-wcag" bind:checked={wcagSelected} value="wcag" />
					<Field.Label for="tool-wcag" class="font-normal">
						WCAG
					</Field.Label>
				</Field.Field>
				<Field.Field orientation="horizontal" class="mb-2">
					<Checkbox name="types" id="tool-domain" checked={form?.values?.types.includes('domain') ?? true} value="domain" />
					<Field.Label for="tool-domain" class="font-normal">
						Domain
					</Field.Label>
				</Field.Field>
				<Field.Field orientation="horizontal" class="mb-2">
					<Checkbox name="types" id="tool-ssl" checked={form?.values?.types.includes('ssl') ?? true} value="ssl" />
					<Field.Label for="tool-ssl" class="font-normal">
						SSL
					</Field.Label>
				</Field.Field>
				<Field.Field orientation="horizontal" class="mb-2">
					<Checkbox name="types" id="tool-whois" value="whois" checked={form?.values?.types.includes('whois')} />
					<Field.Label for="tool-whois" class="font-normal">
						Whois
					</Field.Label>
				</Field.Field>
				<Field.Field orientation="horizontal" class="mb-2">
					<Checkbox name="types" id="tool-security" value="security" checked={form?.values?.types.includes('security')} />
					<Field.Label for="tool-security" class="font-normal">
						Security
					</Field.Label>
				</Field.Field>
				<Field.Field orientation="horizontal" class="mb-2">
					<Checkbox name="types" id="tool-stress" value="stress" checked={form?.values?.types.includes('stress')} />
					<Field.Label for="tool-stress" class="font-normal">
						Stress
					</Field.Label>
				</Field.Field>
			</Field.Group>
			<Field.Separator />
			<Field.Group>
				{#if wcagSelected}
				<div class="flex w-full flex-col gap-1.5">
					<Label for="devices" class="text-lg">WCAG Device Targets</Label>
					<MultiSelect bind:value={selectedDevices} options={deviceOptions} maxSelect={4} />
				</div>
				{#each selectedDevices as device}
				<input type="hidden" name="devices" value={optionValue(device)} />
				{/each}
				{/if}
			</Field.Group>
		</Field.Set>
		<div class="flex items-center gap-3">
			<Button type="submit" size="lg">Create</Button>
			<Button href="/jobs" size="lg" variant="outline">Cancel</Button>
		</div>
	</form>
</div>
